oe_newsroom_newsletter.settings:
  type: config_object
  label: 'Newsroom settings'
  mapping:
    intro_text:
      type: label
      label: 'Introduction text on the subscription page'
    link_classes:
      type: string
      label: 'Extra link classes'
    privacy_uri:
      type: label
      label: 'Privacy url'
    success_subscription_text:
      type: label
      label: 'Message displayed if a subscriber successfully subscribed to the service'
    already_registered_text:
      type: label
      label: 'Message displayed if a subscriber is already subscribed'
